version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - export BUCKET=waynestark-pipeline-0
      - export WEBSITE=waynestark-stark-prototype
      - aws s3 cp api/stark_poc_parser.yml s3://$BUCKET
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - aws s3 cp Vue_sample01_STARK-POC-parser s3://$WEBSITE --recursive --acl public-read
      - aws s3 cp outputtemplate.yml s3://$BUCKET

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
