version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - BUCKET=$(cat template_configuration.json | python3 -c "import sys, json; print(json.load(sys.stdin)['Parameters']['UserCICDPipelineBucketNameParameter'])")
      - WEBSITE=$(cat template_configuration.json | python3 -c "import sys, json; print(json.load(sys.stdin)['Parameters']['UserWebsiteBucketNameParameter'])")
      - CODEGEN=$(cat template_configuration.json | python3 -c "import sys, json; print(json.load(sys.stdin)['Parameters']['UserCodeGenBucketNameParameter'])")
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - cp STARK_Parser/js/STARK_settings_PROD.js STARK_Parser/js/STARK_settings.js
      - aws s3 cp STARK_Parser s3://$WEBSITE --recursive --acl public-read
      - aws s3 cp STARK_SourceBucket_files s3://$CODEGEN/STARKWebSource --recursive
      - aws s3 cp outputtemplate.yml s3://$BUCKET

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
    - template_configuration.json
