version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - export BUCKET=waynestark-pipeline-0
      - export WEBSITE=waynestark-stark-prototype
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - cp STARK_Parser/js/STARK_settings_PROD.js STARK_Parser/js/STARK_settings.js
      - aws s3 cp STARK_Parser s3://$WEBSITE --recursive --acl public-read
      - aws s3 cp outputtemplate.yml s3://$BUCKET

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
    - template_configuration.yml

