AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the STARK infra
Resources:
    STARKParserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 200
                AllowCredentials: False
    STARKParserFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /parser
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Parser
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 60
    STARKCFWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CFWriter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMFullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 60
    STARKDeployFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 600
    STARKDeployCheckFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy_check
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy_Check
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 600
    STARKCodeGenStaticWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Static
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 60
    STARKCodeGenDynamicWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Dynamic
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess 
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:STARK_friendly_to_system_names:2
            Timeout: 60
    STARKBucketPreloaderFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_WebsiteBucketPreloader
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
            Timeout: 60
    ParameterStoreApiID:
        Type: AWS::SSM::Parameter
        Properties:
            Description: API ID of the HttpApi created by STARK-Pipeline-0
            Name: STARKPipeline0_HttpApiID
            Tier: Standard
            Type: String
            Value: !Ref STARKParserApi
Outputs:
    STARKParserApiID:
        Description: API Gateway HttpApi API ID
        Value: !Ref STARKParserApi
        Export:
            Name: STARKParserApiID
