AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the STARK infra
Parameters:
    UserCodeGenBucketNameParameter:
        Type: String
        Description: Name for user bucket that will hold static files and deployment packages created by STARK
    UserCICDPipelineBucketNameParameter:
        Type: String
        Description: Name for user bucket that will be used for the default STARK CI/CD pipeline. Not yet used in template, just needed for config.
    UserWebsiteBucketNameParameter:
        Type: String
        Description: Name for user bucket that will be used as the website bucket for the STARK Parser UI. Not yet used in template, just needed for config.
Resources:
    STARKParserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 200
                AllowCredentials: False
    CFCustomResourceHelperLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/CF_CustomResourceHelper_py38.zip
            Description: Lambda-backed custom resource library for CloudFormation
            LayerName: CF_CustomResourceHelper
    PyYamlLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/yaml_py38.zip
            Description: YAML module for Python 3.x
            LayerName: PyYAML
    STARKFriendlyToSystemNamesLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/STARK_friendly_to_system_name_py38.zip
            Description: STARK module for converting user-supplied, human-friendly identifiers into system-friendly entity or variable names
            LayerName: STARK_friendly_to_system_name
    STARKParserFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /parser
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Parser
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambda_FullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKCFWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CFWriter
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMFullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKDeployFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambda_FullAccess
                - AWSCloudFormationFullAccess
                - IAMFullAccess
                - AmazonS3ReadOnlyAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
    STARKDeployCheckFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy_check
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy_Check
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambda_FullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
    STARKCodeGenStaticWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Static
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKCodeGenDynamicWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Dynamic
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambda_FullAccess 
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKBucketPreloaderFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_WebsiteBucketPreloader
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
    STARKWebsiteUpdaterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_WebsiteUpdater
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
                    API_GATEWAY_ID: !Ref STARKParserApi
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
        DependsOn:
            - STARKParserApi
    ParameterStoreApiID:
        Type: AWS::SSM::Parameter
        Properties:
            Description: API ID of the HttpApi created by STARK-Pipeline-0
            Name: STARKPipeline0_HttpApiID
            Tier: Standard
            Type: String
            Value: !Ref STARKParserApi
    ParameterStoreCFWriterARN:
        Type: AWS::SSM::Parameter
        Properties:
            Description: Invokable name of the CFWriter lambda function. Placed here to avoid hard-coding into the Parser func itself.
            Name: STARK_CFWriter_FunctionName
            Tier: Standard
            Type: String
            Value: !GetAtt STARKCFWriterFunc.Arn
    ParameterStoreBucketPreloaderARN:
        Type: AWS::SSM::Parameter
        Properties:
            Description: Service token for Lambda-backed custom resource that preloads STARK files to the STARK-generated S3 bucket for end-user systems.
            Name: STARK_CustomResource_BucketPreloaderLambda_ARN
            Tier: Standard
            Type: String
            Value: !GetAtt STARKBucketPreloaderFunc.Arn
    ParameterStoreCodeGenDynamicARN:
        Type: AWS::SSM::Parameter
        Properties:
            Description: Service token for Lambda-backed custom resource that creates the STARK-generated Lambda files for end-user systems.
            Name: STARK_CustomResource_CodeGenDynamicLambda_ARN
            Tier: Standard
            Type: String
            Value: !GetAtt STARKCodeGenDynamicWriter.Arn
    ParameterStoreCodeGenStaticARN:
        Type: AWS::SSM::Parameter
        Properties:
            Description: Service token for Lambda-backed custom resource that creates the STARK-generated static files for end-user systems.
            Name: STARK_CustomResource_CodeGenStaticLambda_ARN
            Tier: Standard
            Type: String
            Value: !GetAtt STARKCodeGenStaticWriter.Arn

Outputs:
    STARKParserApiID:
        Description: API Gateway HttpApi API ID
        Value: !Ref STARKParserApi
        Export:
            Name: STARKParserApiID
