AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the STARK infra
Resources:
    STARKParserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 200
                AllowCredentials: False
    CFCustomResourceHelperLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: waynestark-stark-prototype-codegenbucket
                S3Key: CF_CustomResourceHelper_py38.zip
            Description: Lambda-backed custom resource library for CloudFormation
            LayerName: CF_CustomResourceHelper
    PyYamlLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: waynestark-stark-prototype-codegenbucket
                S3Key: yaml_py38.zip
            Description: YAML module for Python 3 
            LayerName: PyYAML
    STARKFriendlyToSystemNamesLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: waynestark-stark-prototype-codegenbucket
                S3Key: STARK_friendly_to_system_name_py38.zip
            Description: STARK module for converting user-supplied, human-friendly identifiers into system-friendly entity or variable names
            LayerName: STARK_friendly_to_system_name
    STARKParserFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /parser
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Parser
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKCFWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CFWriter
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMFullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKDeployFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
    STARKDeployCheckFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy_check
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_Deploy_Check
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
    STARKCodeGenStaticWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Static
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKCodeGenDynamicWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Dynamic
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess 
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
    STARKBucketPreloaderFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: main.lambda_handler
            CodeUri: lambda/STARK_WebsiteBucketPreloader
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
    ParameterStoreApiID:
        Type: AWS::SSM::Parameter
        Properties:
            Description: API ID of the HttpApi created by STARK-Pipeline-0
            Name: STARKPipeline0_HttpApiID
            Tier: Standard
            Type: String
            Value: !Ref STARKParserApi
Outputs:
    STARKParserApiID:
        Description: API Gateway HttpApi API ID
        Value: !Ref STARKParserApi
        Export:
            Name: STARKParserApiID
