AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WIP template for the STARK infra CI/CD pipeline. Will be merged with template.yml and CFWriter when complete, then deleted. 
Resources:
    STARKRepo:
        Type: AWS::CodeCommit::Repository
        Properties:
            RepositoryName: STARK_v1_contributor
            RepositoryDescription: Default Git repo for the STARK tool, for contributors
    STARKBuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: STARK_v1_contributor_build
            Artifacts:
                Type: CODEPIPELINE  
            Description: Default Build Project for the STARK CI/CD Pipeline
            Environment:
                ComputeType: BUILD_GENERAL1_SMALL
                Image: "aws/codebuild/standard:4.0"
                Type: LINUX_CONTAINER
            ServiceRole: arn:aws:iam::201649379729:role/service-role/codebuild-STARK-lambda-pipeline-build-service-role
            Source:
                Type: CODEPIPELINE
    STARKCICDPipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            Name: STARK_v1_contributor_pipeline
            ArtifactStore: 
                Type: S3
                Location: waynestark-pipeline-0
            RoleArn: arn:aws:iam::201649379729:role/service-role/AWSCodePipelineServiceRole-ap-southeast-1-STARK-lambda-pipeline
            Stages:
                -
                    Name: Source
                    Actions:
                        -
                            Name: SourceAction
                            RunOrder: 1
                            ActionTypeId:
                                Category: Source
                                Owner: AWS
                                Provider: CodeCommit
                                Version: '1'
                            Configuration:
                                RepositoryName: !GetAtt STARKRepo.Name
                                PollForSourceChanges: 'true'
                                BranchName: master
                            InputArtifacts: []
                            OutputArtifacts:
                                - Name: SourceArtifact
                -
                    Name: Build
                    Actions:
                        -
                            Name: BuildAction
                            RunOrder: 2
                            ActionTypeId:
                                Category: Build
                                Owner: AWS
                                Provider: CodeBuild
                                Version: '1'
                            Configuration:
                                ProjectName: !Ref STARKBuildProject
                            InputArtifacts:
                                - Name: SourceArtifact
                            OutputArtifacts:
                                - Name: BuildArtifact