AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template to test STARK. Minor test only, just the POC parser
Resources:
    STARKParserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 200
                AllowCredentials: False
    STARKParserFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /parser
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: STARK_parser_v0_3.lambda_handler
            CodeUri: lambda/STARK_POC_parser
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 60
    STARKCFWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_POC_CFwriter
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMFullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 60
    STARKDeployFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: STARK_POC_deploy.lambda_handler
            CodeUri: lambda/STARK_POC_deploy
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 600
    STARKDeployCheckFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy_check
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: STARK_POC_deploy_check.lambda_handler
            CodeUri: lambda/STARK_POC_deploy_check
            Policies:
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess
                - AWSCloudFormationFullAccess
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 600
    STARKCodeGenStaticWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Static
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 60
    STARKCodeGenDynamicWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Dynamic
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaFullAccess 
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:pyyaml_layer_mk1:2
            Timeout: 60
    STARKBucketPreloaderFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_POC_STARKBucketPreloader
            Policies:
                - AmazonS3FullAccess
                - AmazonSSMReadOnlyAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - arn:aws:lambda:ap-southeast-1:201649379729:layer:CF_CustomResourceHelper_layer:1
            Timeout: 60
    STARKModulesFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ModulesGetEvent:
                    Type: HttpApi
                    Properties:
                        Path: /modules
                        Method: GET
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_POC_moduleslist
    STARKCustomerFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                CustomerGetEvent:
                    Type: HttpApi
                    Properties:
                        Path: /customer
                        Method: GET
                        ApiId:
                            Ref: STARKParserApi
                CustomerPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /customer
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
                CustomerPutEvent:
                    Type: HttpApi
                    Properties:
                        Path: /customer
                        Method: PUT
                        ApiId:
                            Ref: STARKParserApi
                CustomerDeleteEvent:
                    Type: HttpApi
                    Properties:
                        Path: /customer
                        Method: DELETE
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.8
            Handler: lambda_function.lambda_handler
            CodeUri: lambda/STARK_POC_customer
            Role: arn:aws:iam::201649379729:role/WayneStark_test_lambda_role_1
    ParameterStoreApiID:
        Type: AWS::SSM::Parameter
        Properties:
            Description: API ID of the HttpApi created by STARK-Pipeline-0
            Name: STARKPipeline0_HttpApiID
            Tier: Standard
            Type: String
            Value: !Ref STARKParserApi
Outputs:
    STARKParserApiID:
        Description: API Gateway HttpApi API ID
        Value: !Ref STARKParserApi
        Export:
            Name: STARKParserApiID
